language: bash
dist: trusty
sudo: required
before_install:
  - chmod +x build.sh
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
install:
  -  ./build.sh
